language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
branches:
  only:
    - master
matrix:
  allow_failures:
    - julia: nightly

before_install:
  - julia -e 'Pkg.clone("https://github.com/rdeits/LCMCore.jl.git")'
  - julia -e 'Pkg.build("LCMCore")'

after_success:
  - julia -e 'cd(Pkg.dir("PyLCM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
